name: Build simple nginx webserver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: build nginx web server 
      run: |
        docker build ./nginx_webserver -t $DOCKER_USER/app:v1_$(date +%s)
        
    - name: nginx image push to registry
      run: |
        docker push $DOCKER_USER/app:v1_$(date +%s)  

      
