name: Build simple nginx webserver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: build top10 books webserver
      run: |
        docker build ./top10_books -t $DOCKER_USER/book_app:v1
    - name: build top10 movies webserver
      run: |
        docker build ./top10_movies -t $DOCKER_USER/movie_app:v1
        
    - name: build top10 songs webserver
      run: |
        docker build ./top10_songs -t $DOCKER_USER/song_app:v1 
        
    - name: nginx image push to registry
      run: |

        docker push $DOCKER_USER/book_app:v1
        docker push $DOCKER_USER/movie_app:v1
        docker push $DOCKER_USER/song_app:v1



      
